// Curated seed roster: publicly known hero/villain/anti-hero classifications
// used to search Comic Vine and tag results with an alignment (Comic Vine's
// own data doesn't include a hero/villain flag). Search queries are chosen
// to be specific enough to land on the well-known version of each character.
//
// This list is intentionally large (not capped to a small handful) so the
// registry reads as a real archive. It's still finite — Comic Vine's full
// database runs into the hundreds of thousands of entries — but every name
// below is resolved from live Comic Vine data, not hardcoded/mocked.
export const ROSTER = [
  // --- Heroes -------------------------------------------------------------
  { query: 'Batman', alignment: 'hero', color: '#212529' },
  { query: 'Superman', alignment: 'hero', color: '#1E90FF' },
  { query: 'Spider-Man', alignment: 'hero', color: '#DC143C' },
  { query: 'Iron Man', alignment: 'hero', color: '#B22222' },
  { query: 'Wonder Woman', alignment: 'hero', color: '#DC143C' },
  { query: 'The Flash', alignment: 'hero', color: '#FF4500' },
  { query: 'Captain America', alignment: 'hero', color: '#1E90FF' },
  { query: 'Wolverine', alignment: 'hero', color: '#FFD700' },
  { query: 'Thor', alignment: 'hero', color: '#4682B4' },
  { query: 'Black Panther', alignment: 'hero', color: '#2a2a36' },
  { query: 'Green Lantern', alignment: 'hero', color: '#00A86B' },
  { query: 'Daredevil', alignment: 'hero', color: '#8B0000' },
  { query: 'Hulk', alignment: 'hero', color: '#355E3B' },
  { query: 'Aquaman', alignment: 'hero', color: '#1E90FF' },
  { query: 'Doctor Strange', alignment: 'hero', color: '#4B0082' },
  { query: 'Black Widow', alignment: 'hero', color: '#2a2a36' },
  { query: 'Captain Marvel', alignment: 'hero', color: '#FFD700' },
  { query: 'Green Arrow', alignment: 'hero', color: '#355E3B' },
  { query: 'Nightwing', alignment: 'hero', color: '#4B0082' },
  { query: 'Supergirl', alignment: 'hero', color: '#1E90FF' },
  { query: 'Cyborg', alignment: 'hero', color: '#4682B4' },
  { query: 'Martian Manhunter', alignment: 'hero', color: '#00A86B' },
  { query: 'Hawkeye', alignment: 'hero', color: '#800020' },
  { query: 'Ant-Man', alignment: 'hero', color: '#B22222' },
  { query: 'Vision', alignment: 'hero', color: '#4B0082' },
  { query: 'Scarlet Witch', alignment: 'hero', color: '#8B0000' },
  { query: 'Star-Lord', alignment: 'hero', color: '#B8860B' },
  { query: 'Gamora', alignment: 'hero', color: '#355E3B' },
  { query: 'Rocket Raccoon', alignment: 'hero', color: '#6C757D' },
  { query: 'Storm', alignment: 'hero', color: '#FFD700' },
  { query: 'Cyclops', alignment: 'hero', color: '#B22222' },
  { query: 'Jean Grey', alignment: 'hero', color: '#B22222' },
  { query: 'Beast (Marvel)', alignment: 'hero', color: '#4682B4' },
  { query: 'Nightcrawler', alignment: 'hero', color: '#4B0082' },
  { query: 'Colossus', alignment: 'hero', color: '#6C757D' },
  { query: 'Falcon (Marvel)', alignment: 'hero', color: '#8B0000' },
  { query: 'Luke Cage', alignment: 'hero', color: '#FFD700' },
  { query: 'Iron Fist', alignment: 'hero', color: '#00A86B' },
  { query: 'Ms. Marvel', alignment: 'hero', color: '#FF4500' },
  { query: 'Shazam', alignment: 'hero', color: '#FFD700' },
  { query: 'Zatanna', alignment: 'hero', color: '#4B0082' },
  { query: 'Blue Beetle', alignment: 'hero', color: '#00A86B' },
  { query: 'Booster Gold', alignment: 'hero', color: '#FFD700' },

  // --- Villains -------------------------------------------------------------
  { query: 'Joker', alignment: 'villain', color: '#4B0082' },
  { query: 'Lex Luthor', alignment: 'villain', color: '#8B0000' },
  { query: 'Thanos', alignment: 'villain', color: '#800020' },
  { query: 'Doctor Doom', alignment: 'villain', color: '#355E3B' },
  { query: 'Magneto', alignment: 'villain', color: '#8B0000' },
  { query: 'Green Goblin', alignment: 'villain', color: '#00A86B' },
  { query: 'Darkseid', alignment: 'villain', color: '#4B0082' },
  { query: 'Loki', alignment: 'villain', color: '#00A86B' },
  { query: 'Ultron', alignment: 'villain', color: '#6C757D' },
  { query: 'Bane (DC)', alignment: 'villain', color: '#8B0000' },
  { query: 'Deathstroke', alignment: 'villain', color: '#FF4500' },
  { query: 'Sinestro', alignment: 'villain', color: '#FFD700' },
  { query: 'Doctor Octopus', alignment: 'villain', color: '#8B0000' },
  { query: 'Red Skull', alignment: 'villain', color: '#8B0000' },
  { query: 'Kingpin', alignment: 'villain', color: '#4B0082' },
  { query: 'Two-Face', alignment: 'villain', color: '#4B0082' },
  { query: 'Riddler', alignment: 'villain', color: '#00A86B' },
  { query: 'Penguin', alignment: 'villain', color: '#212529' },
  { query: 'Scarecrow (DC)', alignment: 'villain', color: '#8B4513' },
  { query: 'Poison Ivy', alignment: 'villain', color: '#355E3B' },
  { query: 'Mystique', alignment: 'villain', color: '#4B0082' },
  { query: 'Apocalypse', alignment: 'villain', color: '#4B0082' },
  { query: 'Mister Sinister', alignment: 'villain', color: '#8B0000' },
  { query: 'Juggernaut', alignment: 'villain', color: '#8B0000' },
  { query: 'Ra\u2019s al Ghul', alignment: 'villain', color: '#355E3B' },
  { query: 'Brainiac', alignment: 'villain', color: '#00A86B' },
  { query: 'Black Adam', alignment: 'villain', color: '#FFD700' },
  { query: 'Reverse-Flash', alignment: 'villain', color: '#8B0000' },
  { query: 'Ronan the Accuser', alignment: 'villain', color: '#4682B4' },
  { query: 'Killmonger', alignment: 'villain', color: '#8B0000' },
  { query: 'Mandarin', alignment: 'villain', color: '#8B0000' },
  { query: 'Vulture (Marvel)', alignment: 'villain', color: '#355E3B' },
  { query: 'Sandman (Marvel)', alignment: 'villain', color: '#B8860B' },

  // --- Anti-heroes ---------------------------------------------------------
  { query: 'Catwoman', alignment: 'anti-hero', color: '#212529' },
  { query: 'Deadpool', alignment: 'anti-hero', color: '#8B0000' },
  { query: 'Venom (Marvel)', alignment: 'anti-hero', color: '#000000' },
  { query: 'Harley Quinn', alignment: 'anti-hero', color: '#FF4500' },
  { query: 'Punisher', alignment: 'anti-hero', color: '#212529' },
  { query: 'Ghost Rider', alignment: 'anti-hero', color: '#FF4500' },
  { query: 'Lobo', alignment: 'anti-hero', color: '#8B0000' },
  { query: 'Elektra', alignment: 'anti-hero', color: '#8B0000' },
  { query: 'Constantine', alignment: 'anti-hero', color: '#355E3B' },
  { query: 'Moon Knight', alignment: 'anti-hero', color: '#F5F5F5' },
]
